# Baseline script of San Francisco Crime Classification

Baseline script. Hope this helps yours.

In [1]:
import numpy as np
import pandas as pd

## Load Data

In [2]:
train = pd.read_csv("train.csv")
train.head(3)

,Dates,Category,Descript,DayOfWeek,PdDistrict,Resolution,Address,X,Y
0,2015-05-13 23:53:00,WARRANTS,WARRANT ARREST,Wednesday,NORTHERN,"ARREST, BOOKED",OAK ST / LAGUNA ST,-122.425892,37.774599
1,2015-05-13 23:53:00,OTHER OFFENSES,TRAFFIC VIOLATION ARREST,Wednesday,NORTHERN,"ARREST, BOOKED",OAK ST / LAGUNA ST,-122.425892,37.774599
2,2015-05-13 23:33:00,OTHER OFFENSES,TRAFFIC VIOLATION ARREST,Wednesday,NORTHERN,"ARREST, BOOKED",VANNESS AV / GREENWICH ST,-122.424363,37.800414

In [3]:
test = pd.read_csv("test.csv")
test.head(3)

,Id,Dates,DayOfWeek,PdDistrict,Address,X,Y
0,0,2015-05-10 23:59:00,Sunday,BAYVIEW,2000 Block of THOMAS AV,-122.399588,37.735051
1,1,2015-05-10 23:51:00,Sunday,BAYVIEW,3RD ST / REVERE AV,-122.391523,37.732432
2,2,2015-05-10 23:50:00,Sunday,NORTHERN,2000 Block of GOUGH ST,-122.426002,37.792212

In [4]:
from sklearn.cross_validation import cross_val_score

feature_names = ["X", "Y"]
label_name = "Category"

train_X = train[feature_names]
test_X = test[feature_names]

train_y = train[label_name]

## Score

In [5]:
from sklearn.naive_bayes import BernoulliNB

model = BernoulliNB()
score = cross_val_score(model, train_X, train_y, scoring='log_loss', cv=5).mean()
print("BernoulliNB = {0:.6f}".format(-1.0 * score))

BernoulliNB = 2.680326

## Prediction

In [6]:
model = BernoulliNB()
model.fit(train_X, train_y)

prediction = model.predict_proba(test_X)
prediction[0:100]

array([[ 0.00172102,  0.0875586 ,  0.00046017, ...,  0.06125366,
         0.04807898,  0.00974177],
       [ 0.00172102,  0.0875586 ,  0.00046017, ...,  0.06125366,
         0.04807898,  0.00974177],
       [ 0.00172102,  0.0875586 ,  0.00046017, ...,  0.06125366,
         0.04807898,  0.00974177],
       ...,
       [ 0.00172102,  0.0875586 ,  0.00046017, ...,  0.06125366,
         0.04807898,  0.00974177],
       [ 0.00172102,  0.0875586 ,  0.00046017, ...,  0.06125366,
         0.04807898,  0.00974177],
       [ 0.00172102,  0.0875586 ,  0.00046017, ...,  0.06125366,
         0.04807898,  0.00974177]])

# Submission

In [7]:
sample = pd.read_csv("sampleSubmission.csv", index_col="Id")
sample.head(3)

,ARSON,ASSAULT,BAD CHECKS,BRIBERY,BURGLARY,DISORDERLY CONDUCT,DRIVING UNDER THE INFLUENCE,DRUG/NARCOTIC,DRUNKENNESS,EMBEZZLEMENT,...,SEX OFFENSES NON FORCIBLE,STOLEN PROPERTY,SUICIDE,SUSPICIOUS OCC,TREA,TRESPASS,VANDALISM,VEHICLE THEFT,WARRANTS,WEAPON LAWS
Id,,,,,,,,,,,,,,,,,,,,,
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0

In [8]:
submission = pd.DataFrame(prediction, index=sample.index)
submission.columns = sample.columns
submission.head()

,ARSON,ASSAULT,BAD CHECKS,BRIBERY,BURGLARY,DISORDERLY CONDUCT,DRIVING UNDER THE INFLUENCE,DRUG/NARCOTIC,DRUNKENNESS,EMBEZZLEMENT,...,SEX OFFENSES NON FORCIBLE,STOLEN PROPERTY,SUICIDE,SUSPICIOUS OCC,TREA,TRESPASS,VANDALISM,VEHICLE THEFT,WARRANTS,WEAPON LAWS
Id,,,,,,,,,,,,,,,,,,,,,
0,0.001721,0.087559,0.00046,0.000327,0.041861,0.004918,0.002581,0.06147,0.004873,0.001326,...,0.000166,0.005169,0.000576,0.035778,0.000005,0.008342,0.050939,0.061254,0.048079,0.009742
1,0.001721,0.087559,0.00046,0.000327,0.041861,0.004918,0.002581,0.06147,0.004873,0.001326,...,0.000166,0.005169,0.000576,0.035778,0.000005,0.008342,0.050939,0.061254,0.048079,0.009742
2,0.001721,0.087559,0.00046,0.000327,0.041861,0.004918,0.002581,0.06147,0.004873,0.001326,...,0.000166,0.005169,0.000576,0.035778,0.000005,0.008342,0.050939,0.061254,0.048079,0.009742
3,0.001721,0.087559,0.00046,0.000327,0.041861,0.004918,0.002581,0.06147,0.004873,0.001326,...,0.000166,0.005169,0.000576,0.035778,0.000005,0.008342,0.050939,0.061254,0.048079,0.009742
4,0.001721,0.087559,0.00046,0.000327,0.041861,0.004918,0.002581,0.06147,0.004873,0.001326,...,0.000166,0.005169,0.000576,0.035778,0.000005,0.008342,0.050939,0.061254,0.048079,0.009742

In [9]:
from datetime import datetime

current_time = datetime.now().strftime("%Y.%m.%d %H:%M:%S")
description = "baseline script"

filename = "{0} {1}.csv".format(current_time, description)

submission.to_csv(filename)